[project]
name = "Satoshi_Escrow"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.satoshi-escrow]
path = "contracts/satoshi-escrow.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }